# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20161125_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
