# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_submission_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
