# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_remove_song_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewing_organizations', through='organizations.Reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
