# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0010_organization_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.Charge'),
        ),
    ]
